/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cs.gui.Iframes;

import com.cs.dao.Product;

import com.cs.gui.frmMain;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author home
 */
public class frmIProduct extends javax.swing.JInternalFrame {

    private final EntityManager em = frmMain.emf.createEntityManager();
    private List<Product> prodList = new ArrayList<>();
    Product selectedProduct;

    /**
     * Creates new form frmIProduct
     */
    public frmIProduct() {
        initComponents();
        Query query = em.createNamedQuery("Product.findAll");
        prodList = (List<Product>)query.getResultList();
        loadProductTable(null);
        tblMain.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!optAdd.isSelected() && tblMain.getSelectedRow() > -1) {
                    String name = (String) tblMain.getValueAt(tblMain.getSelectedRow(), 1);
                    selectedProduct = findProduct(name);
//                    txtName.setText(selectedProduct.getProductName());
//                    txtBPrice.setText(selectedProduct.getBprice()+"");
//                    txtSPrice.setText(selectedProduct.getSprice()+"");
//                    txtQTY.setText(selectedProduct.getQty()+"");
                }

            }
        });

    }
    
    Product findProduct(String name) {
//        for (Product product : prodList) {
//            if (product.getProductName().equals(name)) {
//                return product;
//            }
//        }
        return null;
    }
    
    void loadProductTable(String name) {

        DefaultTableModel tblModel = (DefaultTableModel) tblMain.getModel();
        tblModel.setRowCount(0);
//        for (Product prod : prodList) {
//            if (name == null) {
//                tblModel.addRow(new Object[]{prod.getProductPK().getProductId(), prod.getProductName(), prod.getBprice(), prod.getSprice(), prod.getQty() });
//
//            } else if (prod.getProductName().toLowerCase().startsWith(name.toLowerCase())) {
//
//                tblModel.addRow(new Object[]{prod.getProductPK().getProductId(), prod.getProductName(), prod.getBprice(), prod.getSprice(), prod.getQty() });
//            }
//        }

    }

    void enableALl() {
        txtBPrice.setEnabled(true);
        txtFindBy.setEnabled(true);
        txtName.setEnabled(true);
        txtQTY.setEnabled(true);
        txtSPrice.setEnabled(true);
    }

    void desableALl() {
        txtBPrice.setEnabled(false);
        txtFindBy.setEnabled(false);
        txtName.setEnabled(false);
        txtQTY.setEnabled(false);
        txtSPrice.setEnabled(false);
    }

    void clearALl() {
        txtName.setText("");
        txtBPrice.setText("");
        txtFindBy.setText("");
        txtQTY.setText("");
        txtSPrice.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFindBy = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        optUpdate = new javax.swing.JRadioButton();
        optAdd = new javax.swing.JRadioButton();
        optDelete = new javax.swing.JRadioButton();
        txtQTY = new javax.swing.JFormattedTextField();
        txtBPrice = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSPrice = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Products");

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "BPrice", "SPrice", "QTY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMain);
        if (tblMain.getColumnModel().getColumnCount() > 0) {
            tblMain.getColumnModel().getColumn(0).setResizable(false);
            tblMain.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblMain.getColumnModel().getColumn(1).setResizable(false);
            tblMain.getColumnModel().getColumn(1).setPreferredWidth(30);
            tblMain.getColumnModel().getColumn(2).setResizable(false);
            tblMain.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblMain.getColumnModel().getColumn(3).setResizable(false);
            tblMain.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Name");

        jLabel2.setText("Buying Price");

        jLabel6.setText("Find By Name");

        txtFindBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindByActionPerformed(evt);
            }
        });
        txtFindBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindByKeyReleased(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("QTY");

        buttonGroup1.add(optUpdate);
        optUpdate.setText("Update");
        optUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optUpdateActionPerformed(evt);
            }
        });

        buttonGroup1.add(optAdd);
        optAdd.setText("Add");
        optAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAddActionPerformed(evt);
            }
        });

        buttonGroup1.add(optDelete);
        optDelete.setText("Delete");
        optDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDeleteActionPerformed(evt);
            }
        });

        txtQTY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtBPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel9.setText("Selling Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(txtFindBy))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optAdd)
                                .addGap(32, 32, 32)
                                .addComponent(optDelete)
                                .addGap(40, 40, 40)
                                .addComponent(optUpdate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optAdd)
                    .addComponent(optDelete)
                    .addComponent(optUpdate))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFindBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtBPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindByActionPerformed

    private void optUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optUpdateActionPerformed
        btnSave.setText("Update");
    }//GEN-LAST:event_optUpdateActionPerformed

    private void optAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAddActionPerformed
        btnSave.setText("Add");
        clearALl();
    }//GEN-LAST:event_optAddActionPerformed

    private void optDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDeleteActionPerformed
        btnSave.setText("Delete");
    }//GEN-LAST:event_optDeleteActionPerformed

    private void txtFindByKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindByKeyReleased
        loadProductTable(txtFindBy.getText());
    }//GEN-LAST:event_txtFindByKeyReleased

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
    }//GEN-LAST:event_tblMainMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "You Must Provide A Product Name");
            return;
        }

        if (optAdd.isSelected()) {
//            em.getTransaction().begin();
//            Product product = new Product();
//            product.setProductPK(new ProductPK());
//            product.setProductName(txtName.getText());
//            product.setBprice(Double.parseDouble(txtBPrice.getText()));
//            product.setSprice(Double.parseDouble(txtSPrice.getText()));
//            product.setQty(Integer.parseInt(txtQTY.getText()));
//            
//            em.persist(product);
//            em.getTransaction().commit();
//            prodList.add(product);
//            loadProductTable(null);
            JOptionPane.showMessageDialog(this, "Product Added", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

        if (optUpdate.isSelected() && selectedProduct != null) {
            em.getTransaction().begin();
//
//            selectedProduct.setProductName(txtName.getText());
//            selectedProduct.setBprice(Double.parseDouble(txtBPrice.getText()));
//            selectedProduct.setSprice(Double.parseDouble(txtSPrice.getText()));
//            selectedProduct.setQty(Integer.parseInt(txtQTY.getText()));
            
            em.persist(selectedProduct);
            em.getTransaction().commit();
            prodList.remove(selectedProduct);
            prodList.add(selectedProduct);
            loadProductTable(null);
            JOptionPane.showMessageDialog(this, "Product Updated", "Success", JOptionPane.INFORMATION_MESSAGE);
            selectedProduct = null;
        }

        if (optDelete.isSelected() && selectedProduct != null) {
            em.getTransaction().begin();

            em.remove(selectedProduct);
            em.getTransaction().commit();
            prodList.remove(selectedProduct);
            loadProductTable(null);
            JOptionPane.showMessageDialog(this, "Product Deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
            selectedProduct = null;
        }
        clearALl();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton optAdd;
    private javax.swing.JRadioButton optDelete;
    private javax.swing.JRadioButton optUpdate;
    private javax.swing.JTable tblMain;
    private javax.swing.JFormattedTextField txtBPrice;
    private javax.swing.JTextField txtFindBy;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtQTY;
    private javax.swing.JTextField txtSPrice;
    // End of variables declaration//GEN-END:variables
}
