/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cs.gui;


import com.cs.gui.Iframes.frmICustomer;
import com.cs.gui.Iframes.frmIGRN;
import com.cs.gui.Iframes.frmIInvoice;
import com.cs.gui.Iframes.frmIProduct;
import com.cs.gui.Iframes.frmIProductCatagory;
import com.cs.gui.Iframes.frmIRole;
import com.cs.gui.Iframes.frmIUsers;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;

import javax.swing.JInternalFrame;


/**
 *
 * @author home
 */
public class frmMain extends javax.swing.JFrame {
    public static EntityManagerFactory emf = Persistence.createEntityManagerFactory("CShopPU");
   
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktopPane = new javax.swing.JDesktopPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuIProducts = new javax.swing.JMenuItem();
        mnuICustomer = new javax.swing.JMenuItem();
        mnuIUser = new javax.swing.JMenuItem();
        mnuIRoles = new javax.swing.JMenuItem();
        mnuIProductCategory = new javax.swing.JMenuItem();
        mnuiInvoice = new javax.swing.JMenuItem();
        mnuISuppluer = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print Shop");
        setExtendedState(2);

        mainDesktopPane.setBackground(new java.awt.Color(235, 255, 255));

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1383, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mnuIProducts.setText("Products");
        mnuIProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIProductsActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIProducts);

        mnuICustomer.setText("Customers");
        mnuICustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuICustomerActionPerformed(evt);
            }
        });
        mnuFile.add(mnuICustomer);

        mnuIUser.setText("Users");
        mnuIUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIUserActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIUser);

        mnuIRoles.setText("Roles");
        mnuIRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIRolesActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIRoles);

        mnuIProductCategory.setText("Product Category");
        mnuIProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIProductCategoryActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIProductCategory);

        mnuiInvoice.setText("Invoice");
        mnuiInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiInvoiceActionPerformed(evt);
            }
        });
        mnuFile.add(mnuiInvoice);

        mnuISuppluer.setText("Supplier");
        mnuISuppluer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuISuppluerActionPerformed(evt);
            }
        });
        mnuFile.add(mnuISuppluer);

        jMenuItem1.setText("GRN");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuFile.add(jMenuItem1);

        mnuBar.add(mnuFile);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIProductsActionPerformed
        showIFrame(new frmIProduct());
    }//GEN-LAST:event_mnuIProductsActionPerformed

    private void mnuICustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuICustomerActionPerformed
        showIFrame(new frmICustomer(true));
    }//GEN-LAST:event_mnuICustomerActionPerformed

    private void mnuIRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIRolesActionPerformed
        showIFrame(new frmIRole());
    }//GEN-LAST:event_mnuIRolesActionPerformed

    private void mnuiInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiInvoiceActionPerformed
        showIFrame(new frmIInvoice());
    }//GEN-LAST:event_mnuiInvoiceActionPerformed

    private void mnuIProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIProductCategoryActionPerformed
         showIFrame(new frmIProductCatagory());
    }//GEN-LAST:event_mnuIProductCategoryActionPerformed

    private void mnuIUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIUserActionPerformed
         showIFrame(new frmIUsers());
    }//GEN-LAST:event_mnuIUserActionPerformed

    private void mnuISuppluerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuISuppluerActionPerformed
        showIFrame(new frmICustomer(false));
    }//GEN-LAST:event_mnuISuppluerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        showIFrame(new frmIGRN());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMain frm = new  frmMain();
                frm.setVisible(true);
                frm.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    public static void showIFrame(JInternalFrame frame) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    frame.setVisible(true);
                    mainDesktopPane.add(frame);
                    frame.setSelected(true);
                    Dimension desktopSize = mainDesktopPane.getSize();
                    Dimension jInternalFrameSize = frame.getSize();
                    frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                            (desktopSize.height - jInternalFrameSize.height) / 2);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public static void showIFrameMax(JInternalFrame frame) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    frame.setVisible(true);
                    mainDesktopPane.add(frame);
                    frame.setSelected(true);
                    Dimension desktopSize = mainDesktopPane.getSize();
                    Dimension jInternalFrameSize = frame.getSize();
                    frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                            (desktopSize.height - jInternalFrameSize.height) / 2);
                    frame.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuICustomer;
    private javax.swing.JMenuItem mnuIProductCategory;
    private javax.swing.JMenuItem mnuIProducts;
    private javax.swing.JMenuItem mnuIRoles;
    private javax.swing.JMenuItem mnuISuppluer;
    private javax.swing.JMenuItem mnuIUser;
    private javax.swing.JMenuItem mnuiInvoice;
    // End of variables declaration//GEN-END:variables
}