/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cs.gui;


import com.cs.gui.Iframes.frmICustomer;
import com.cs.gui.Iframes.frmIPaymentMethods;
import com.cs.gui.Iframes.frmIProduct;
import com.cs.gui.Iframes.frmIProductCatagory;
import com.cs.gui.Iframes.frmIRole;
import com.cs.gui.Iframes.frmIUsers;
import com.cs.gui.Iframes.frmIInvoice;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JInternalFrame;


/**
 *
 * @author home
 */
public class frmMain extends javax.swing.JFrame {

   
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktopPane = new javax.swing.JDesktopPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuIProducts = new javax.swing.JMenuItem();
        mnuICustomer = new javax.swing.JMenuItem();
        mnuIPaymentMethod = new javax.swing.JMenuItem();
        mnuIProductCatagory = new javax.swing.JMenuItem();
        mnuIRoles = new javax.swing.JMenuItem();
        mnuIUsers = new javax.swing.JMenuItem();
        mnuIInvoice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print Shop");
        setExtendedState(2);

        mainDesktopPane.setBackground(new java.awt.Color(235, 255, 255));

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1383, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mnuIProducts.setText("Products");
        mnuIProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIProductsActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIProducts);

        mnuICustomer.setText("Customer");
        mnuICustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuICustomerActionPerformed(evt);
            }
        });
        mnuFile.add(mnuICustomer);

        mnuIPaymentMethod.setText("Payment Methods");
        mnuIPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIPaymentMethodActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIPaymentMethod);

        mnuIProductCatagory.setText("Product Catagory");
        mnuIProductCatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIProductCatagoryActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIProductCatagory);

        mnuIRoles.setText("Roles");
        mnuIRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIRolesActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIRoles);

        mnuIUsers.setText("Users");
        mnuIUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIUsersActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIUsers);

        mnuIInvoice.setText("Invoice");
        mnuIInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIInvoiceActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIInvoice);

        mnuBar.add(mnuFile);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIProductsActionPerformed
        showIFrame(new frmIProduct());
    }//GEN-LAST:event_mnuIProductsActionPerformed

    private void mnuICustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuICustomerActionPerformed
        showIFrame(new frmICustomer());
    }//GEN-LAST:event_mnuICustomerActionPerformed

    private void mnuIProductCatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIProductCatagoryActionPerformed
        showIFrame(new frmIProductCatagory());
    }//GEN-LAST:event_mnuIProductCatagoryActionPerformed

    private void mnuIPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIPaymentMethodActionPerformed
        showIFrame(new frmIPaymentMethods());
    }//GEN-LAST:event_mnuIPaymentMethodActionPerformed

    private void mnuIRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIRolesActionPerformed
       showIFrame(new frmIRole());
    }//GEN-LAST:event_mnuIRolesActionPerformed

    private void mnuIUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIUsersActionPerformed
        showIFrame(new frmIUsers());
    }//GEN-LAST:event_mnuIUsersActionPerformed

    private void mnuIInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIInvoiceActionPerformed
        showIFrame(new frmIInvoice());
    }//GEN-LAST:event_mnuIInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    public static void showIFrame(JInternalFrame frame) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    frame.setVisible(true);
                    mainDesktopPane.add(frame);
                    frame.setSelected(true);
                    Dimension desktopSize = mainDesktopPane.getSize();
                    Dimension jInternalFrameSize = frame.getSize();
                    frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                            (desktopSize.height - jInternalFrameSize.height) / 2);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public static void showIFrameMax(JInternalFrame frame) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    frame.setVisible(true);
                    mainDesktopPane.add(frame);
                    frame.setSelected(true);
                    Dimension desktopSize = mainDesktopPane.getSize();
                    Dimension jInternalFrameSize = frame.getSize();
                    frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                            (desktopSize.height - jInternalFrameSize.height) / 2);
                    frame.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuICustomer;
    private javax.swing.JMenuItem mnuIInvoice;
    private javax.swing.JMenuItem mnuIPaymentMethod;
    private javax.swing.JMenuItem mnuIProductCatagory;
    private javax.swing.JMenuItem mnuIProducts;
    private javax.swing.JMenuItem mnuIRoles;
    private javax.swing.JMenuItem mnuIUsers;
    // End of variables declaration//GEN-END:variables
}
